---
title: "R-Curious"
subtitle: "What you need to know ahead of the workshop"
date: "`r  dontpanic::title_date()`"
author: "Sarah Kaiser and Charles T. Gray"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

R-Curious aims to arm the newcomer to R with an understanding of how to undertake (and troubleshoot) the data-analysis process in R, step by step.

Beginning with installation, we will get set up with R and RStudio, import some data, and introduce a few exploratory data analysis techniques. At each point we will stop and discuss the various challenges that may be thrown up when you sit down on your own to do data analysis within for your research.  

We want you to feel empowered to troubleshoot your own analysis using cheatsheets, the community, and most of all, an idea of what to go looking for. 

Here are some installation instructions, with which you can get setup ahead of the workshop, if you wish. 

If you don't have time, or your ragequit the installation process (a most necessary sanity-preserving coding technique), don't worry, we'll cover this as part of the workshop. If you're set up ahead of time, you can help us assist those who still need to run through the installation process. 

## Installation overview

- install R (quick) 
- install RStudio (a little while)

Installation instructions [adapted](https://github.com/rladies/meetup-presentations_london/blob/master/2016-04_Beginners_DropIn/April_DropIn.Rmd) with appreciation from a previous workshop. 

## Install R on Mac or Windows

Go to the [Comprehensive R Archive Network](https://cran.r-project.org/)(CRAN) website.

It was first in a google search for 'cran' in June 2018.

***

### For Mac users

- Click on **Download R for (Mac) OS X** 
- Look at the top link under **Latest release**, which at time of writing is **R-3.5.0.pkg**, and download this if compatible with your current version mac OS (Mavericks 10.9 or higher). Otherwise download the version beneath it which is compatible for older mac OS versions. 

### For Windows users

- Click on **Download R for Windows** 
- Then click on the link **install R for the first time** 
- Download from the large link at the top of the page which at time of writing is **Download R 3.5.0 for Windows**. 

## Install R

- Then double click the downloaded **R-3.5.0.pkg** file and follow the prompts to install the downloaded software.

## Download & Install RStudio:

Go to the [RStudio](https://www.rstudio.com/) website.  

It was first in a google search for 'rstudio' in June 2018.

Choose **RStudio** and scroll down to the blue **Download RStudio Desktop** button. 

Click the green button to download **RStudio Desktop Open Source License** and select appropriate installer for your operating system.

Double click the installer and follow the prompts to set up RStudio. 
